### ISSUE TITLE
[Feature Request] ItemsAdder Emoji support

### ISSUE THREAD

**Issue by FaultyFunctions** [max1mde/ChatBubbles-API#2]
With ItemsAdder you can add emoji's to your chat (basically font images from a resource pack). You can use it like `:smiley:` in the chat and it replaces the words `:smiley:` with the actual font image. However, with the chat bubbles it still just says `:smiley:` instead of displaying the image. Would this be able to be added?

Here is the API Repo: https://github.com/LoneDev6/API-ItemsAdder

I believe the relevant API class is here: https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/FontImages/FontImageWrapper.java

**Comment by max1mde** [comment]
Can you please join the [Discord](https://discord.gg/6j3GhhYVMj) server for testing it with ItemsAdder? Because I'll have to send you the plugin somehow (Can't just upload it here)

**Comment by FaultyFunctions** [comment]
Sure thing!
