### ISSUE TITLE
[Bug] If you try to dismount an entity while the chat bubble is up, it breaks dismounting entities for the entire server.

### ISSUE THREAD

**Issue by FaultyFunctions** [max1mde/ChatBubbles-API#5]
Hello! So I'm running purpur 1.20.4 2176. If you try to dismount a horse or boat or anything dismountable while the chat bubble is up, you get stuck riding the thing. The only way to fix it is to relog or have someone else break the boat. While you are in this bugged state, you can move like on a boat for instance but others will see you standing in place just rotating. Then when you break the boat of the bugged player, they will teleport back to their original location..

Any ideas on how to fix this?

**Comment by max1mde** [comment]
Updates?
